title: Yuanqing Feng (冯园庆)
email: Fengyuanqing2010@gmail.com
description: >- 
  Research Associate at University of Pennsylvania, focusing on genetic mechanisms underlying human evolution, phenotypic diversity, and disease susceptibility.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fengyq.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
navigation:
  - title: Home
    url: /
  - title: Research
    url: /research/
  - title: Publication
    url: /publications/
  - title: People
    url: /people/

# Social links
social_links:
  google_scholar: nWYWiVUAAAAJ
  github: fengyq
  linkedin: yuanqing-feng-a4384477
  twitter: FengYuanqing
  wechat: FengYuanqing

# Other settings
show_excerpts: true 
permalink: /:categories/:year/:month/:day/:title/   